"use client";

import { useEffect, useState } from "react";
import { toast } from "sonner";

import Link from "next/link";

import Card from "@/components/ui/Card";

import {
  ClinicInvoice,
  getInvoices,
} from "@/services/billing";

import { getClinicSettings } from "@/services/settings";

export default function InvoiceListPage() {
  const [loading, setLoading] =
    useState(true);

  const [invoices, setInvoices] =
    useState<ClinicInvoice[]>([]);

  const [currency, setCurrency] =
    useState("KES");

  async function loadInvoices() {
    try {
      setLoading(true);

      const [result, clinicSettings] =
        await Promise.all([
          getInvoices(),
          getClinicSettings(),
        ]);

      setInvoices(result);
      setCurrency(
        clinicSettings.currency || "KES"
      );
    } catch (error) {
      console.error(error);

      toast.error(
        error instanceof Error
          ? error.message
          : "Failed to load invoices."
      );
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadInvoices();
  }, []);

  const formatCurrency = (amount: number) =>
    new Intl.NumberFormat(undefined, {
      style: "currency",
      currency,
      maximumFractionDigits: 0,
    }).format(amount);

  return (
    <div className="space-y-8">

      <div>

        <h1 className="text-3xl font-bold">
          Invoices
        </h1>

        <p className="mt-2 text-slate-500">
          All invoices generated by
          your clinic.
        </p>

      </div>

      <Card title="Invoices">

        {loading ? (

          <div className="py-12 text-center">
            Loading...
          </div>

        ) : invoices.length === 0 ? (

          <div className="py-12 text-center text-slate-500">
            No invoices found.
          </div>

        ) : (

          <div className="space-y-3">

            {invoices.map(
              (invoice) => (

                <Link
                  key={invoice.id}
                  href={`/admin/billing/${invoice.id}`}
                  className="flex items-center justify-between rounded-xl border border-slate-200 p-5 transition hover:bg-slate-50"
                >

                  <div>

                    <h3 className="font-semibold">
                      {
                        invoice.invoice_number
                      }
                    </h3>

                    <p className="text-sm text-slate-500">
                      {new Date(
                        invoice.created_at
                      ).toLocaleDateString()}
                    </p>

                  </div>

                  <div className="text-right">

                    <p className="font-bold">
                      {formatCurrency(
                        Number(invoice.total)
                      )}
                    </p>

                    <p
                      className={`text-sm font-semibold ${
                        invoice.status ===
                        "Paid"
                          ? "text-green-600"
                          : invoice.status ===
                            "Partially Paid"
                          ? "text-amber-600"
                          : "text-red-600"
                      }`}
                    >
                      {
                        invoice.status
                      }
                    </p>

                    {invoice.payment_method === "Insurance" &&
                      invoice.insurance_provider?.name && (
                        <p className="text-xs text-slate-500">
                          Insurance · {invoice.insurance_provider.name}
                        </p>
                      )}

                  </div>

                </Link>

              )
            )}

          </div>

        )}

      </Card>

    </div>
  );
}