"use client";

import { useCallback, useEffect, useState } from "react";
import { toast } from "sonner";

import Link from "next/link";

import Card from "@/components/ui/Card";
import Button from "@/components/ui/Button";
import PermissionGuard from "@/components/auth/PermissionGuard";

import {
  ClinicInvoice,
  getInvoices,
} from "@/services/billing";

import { getClinicSettings } from "@/services/settings";
import { getSafeErrorMessage } from "@/lib/logError";

const PAGE_SIZE = 50;

function InvoiceListPageContent() {
  const [loading, setLoading] =
    useState(true);

  const [invoices, setInvoices] =
    useState<ClinicInvoice[]>([]);

  const [totalInvoices, setTotalInvoices] =
    useState(0);

  const [currentPage, setCurrentPage] =
    useState(1);

  const [currency, setCurrency] =
    useState("KES");

  const loadInvoices = useCallback(async (page: number) => {
    try {
      setLoading(true);

      const [{ rows, count }, clinicSettings] =
        await Promise.all([
          getInvoices(page, PAGE_SIZE),
          getClinicSettings(),
        ]);

      setInvoices(rows);
      setTotalInvoices(count);
      setCurrency(
        clinicSettings.currency || "KES"
      );
    } catch (error) {
      toast.error(
        getSafeErrorMessage(error, "Failed to load invoices.")
      );
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadInvoices(currentPage);
  }, [currentPage, loadInvoices]);

  const formatCurrency = (amount: number) =>
    new Intl.NumberFormat(undefined, {
      style: "currency",
      currency,
      maximumFractionDigits: 0,
    }).format(amount);

  const totalPages = Math.max(1, Math.ceil(totalInvoices / PAGE_SIZE));

  return (
    <div className="space-y-8">

      <div>

        <h1 className="text-3xl font-bold">
          Invoices
        </h1>

        <p className="mt-2 text-slate-500">
          All invoices generated by
          your clinic.
        </p>

      </div>

      <Card title="Invoices">

        {loading ? (

          <div className="py-12 text-center">
            Loading...
          </div>

        ) : invoices.length === 0 ? (

          <div className="py-12 text-center text-slate-500">
            No invoices found.
          </div>

        ) : (

          <div className="space-y-3">

            {invoices.map(
              (invoice) => (

                <Link
                  key={invoice.id}
                  href={`/admin/billing/${invoice.id}`}
                  className="flex items-center justify-between rounded-xl border border-slate-200 p-5 transition hover:bg-slate-50"
                >

                  <div>

                    <h3 className="font-semibold">
                      {
                        invoice.invoice_number
                      }
                    </h3>

                    <p className="text-sm text-slate-500">
                      {new Date(
                        invoice.created_at
                      ).toLocaleDateString()}
                    </p>

                  </div>

                  <div className="text-right">

                    <p className="font-bold">
                      {formatCurrency(
                        Number(invoice.total)
                      )}
                    </p>

                    <p
                      className={`text-sm font-semibold ${
                        invoice.status ===
                        "Paid"
                          ? "text-green-600"
                          : invoice.status ===
                            "Partially Paid"
                          ? "text-amber-600"
                          : "text-red-600"
                      }`}
                    >
                      {
                        invoice.status
                      }
                    </p>

                    {invoice.payment_method === "Insurance" &&
                      invoice.insurance_provider?.name && (
                        <p className="text-xs text-slate-500">
                          Insurance · {invoice.insurance_provider.name}
                        </p>
                      )}

                  </div>

                </Link>

              )
            )}

          </div>

        )}

      </Card>

      {!loading && totalInvoices > 0 && (
        <div className="flex items-center justify-between rounded-xl border border-slate-200 bg-white p-4">

          <div className="text-sm text-slate-600">
            Showing{" "}
            <span className="font-semibold">
              {(currentPage - 1) * PAGE_SIZE + 1}
            </span>
            {" - "}
            <span className="font-semibold">
              {Math.min(currentPage * PAGE_SIZE, totalInvoices)}
            </span>
            {" "}of{" "}
            <span className="font-semibold">
              {totalInvoices.toLocaleString()}
            </span>
          </div>

          <div className="flex items-center gap-3">

            <Button
              disabled={currentPage === 1}
              onClick={() =>
                setCurrentPage((page) => Math.max(1, page - 1))
              }
            >
              Previous
            </Button>

            <div className="text-sm font-medium">
              Page {currentPage} of {totalPages}
            </div>

            <Button
              disabled={currentPage >= totalPages}
              onClick={() =>
                setCurrentPage((page) => Math.min(totalPages, page + 1))
              }
            >
              Next
            </Button>

          </div>

        </div>
      )}

    </div>
  );
}

export default function InvoiceListPage() {
  return (
    <PermissionGuard permission="billing">
      <InvoiceListPageContent />
    </PermissionGuard>
  );
}
