import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

import { ReportResult, ReportSection } from "@/types/reports";
import { formatReportCell } from "./format";

const MARGIN = 40;

function docWithLastTable(doc: jsPDF) {
  return doc as unknown as { lastAutoTable?: { finalY: number } };
}

function drawTable(
  doc: jsPDF,
  startY: number,
  columns: ReportSection["columns"],
  rows: ReportSection["rows"],
  currency: string,
  totalsRow?: Record<string, string | number | null>
): number {
  const body = rows.map((row) =>
    columns.map((column) =>
      formatReportCell(row[column.key] ?? null, column.format, currency)
    )
  );

  const foot = totalsRow
    ? [
        columns.map((column) =>
          formatReportCell(totalsRow[column.key] ?? null, column.format, currency)
        ),
      ]
    : undefined;

  autoTable(doc, {
    startY,
    margin: { left: MARGIN, right: MARGIN, top: MARGIN, bottom: MARGIN },
    head: [columns.map((column) => column.label)],
    body,
    foot,
    showHead: "everyPage",
    showFoot: foot ? "lastPage" : "never",
    theme: "grid",
    styles: { fontSize: 8, cellPadding: 4, overflow: "linebreak" },
    headStyles: { fillColor: [23, 92, 74], textColor: 255, fontStyle: "bold" },
    footStyles: { fillColor: [230, 240, 237], textColor: 20, fontStyle: "bold" },
    columnStyles: Object.fromEntries(
      columns.map((column, index) => [
        index,
        {
          halign:
            column.format === "currency" ||
            column.format === "number" ||
            column.format === "percent"
              ? "right"
              : "left",
        },
      ])
    ),
  });

  return docWithLastTable(doc).lastAutoTable?.finalY ?? startY + 20;
}

/**
 * A real PDF document (jsPDF + jspdf-autotable), not a screenshot of the
 * browser page - repeating table headers, automatic page breaks, and
 * per-report-width orientation (landscape once a report has enough
 * columns that portrait would start clipping them) are all handled by
 * autoTable itself rather than hand-rolled pagination logic.
 */
export function exportReportToPdf(report: ReportResult): void {
  const wide = report.columns.length > 6;

  const doc = new jsPDF({
    orientation: wide ? "landscape" : "portrait",
    unit: "pt",
    format: "a4",
  });

  doc.setFontSize(18);
  doc.setTextColor(23, 92, 74);
  doc.text(report.clinicName, MARGIN, MARGIN);

  doc.setFontSize(13);
  doc.setTextColor(20, 20, 20);
  doc.text(report.title, MARGIN, MARGIN + 22);

  doc.setFontSize(9);
  doc.setTextColor(90, 90, 90);
  doc.text(`Period: ${report.dateRangeLabel}`, MARGIN, MARGIN + 40);
  doc.text(
    `Generated: ${new Date(report.generatedAt).toLocaleString()}`,
    MARGIN,
    MARGIN + 54
  );

  let y = MARGIN + 74;

  if (report.summaryCards.length > 0) {
    autoTable(doc, {
      startY: y,
      margin: { left: MARGIN, right: MARGIN },
      theme: "plain",
      styles: { fontSize: 9, cellPadding: 4 },
      body: report.summaryCards.map((card) => [card.label, card.value]),
      columnStyles: {
        0: { fontStyle: "bold", textColor: [90, 90, 90] },
        1: { fontStyle: "bold", halign: "right" },
      },
    });

    y = docWithLastTable(doc).lastAutoTable?.finalY ?? y + 40;
    y += 12;
  }

  if (report.notices && report.notices.length > 0) {
    doc.setFontSize(8);
    for (const notice of report.notices) {
      doc.setTextColor(notice.tone === "warning" ? 176 : 90, notice.tone === "warning" ? 100 : 90, 40);
      const lines = doc.splitTextToSize(
        `${notice.tone === "warning" ? "Note: " : ""}${notice.message}`,
        doc.internal.pageSize.getWidth() - MARGIN * 2
      );
      doc.text(lines, MARGIN, y);
      y += lines.length * 11 + 4;
    }
    doc.setTextColor(20, 20, 20);
    y += 8;
  }

  y = drawTable(doc, y, report.columns, report.rows, report.currency, report.totalsRow);

  for (const section of report.sections ?? []) {
    y += 20;

    if (y > doc.internal.pageSize.getHeight() - MARGIN * 2) {
      doc.addPage();
      y = MARGIN;
    }

    doc.setFontSize(11);
    doc.setTextColor(23, 92, 74);
    doc.text(section.title, MARGIN, y);
    y += 14;

    y = drawTable(doc, y, section.columns, section.rows, report.currency);
  }

  const pageCount = doc.getNumberOfPages();
  for (let page = 1; page <= pageCount; page++) {
    doc.setPage(page);
    doc.setFontSize(8);
    doc.setTextColor(140, 140, 140);
    doc.text(
      `Page ${page} of ${pageCount} · Generated by DentalFlow`,
      MARGIN,
      doc.internal.pageSize.getHeight() - 20
    );
  }

  doc.save(`${report.title.replace(/\s+/g, "-")}-${report.generatedAt.slice(0, 10)}.pdf`);
}
